app_id = "com.github.kdwk.Spidey"

icons = ["plus", "left", "right", "cross", "multitasking-windows", "about", "screenshooter", "move-to-window", "menu", "arrow3-right", "copy", "padlock2", "padlock2-open", "arrows-pointing-outward", "arrows-pointing-inward", "pin", "arrow-circular-top-right"]
